describe('login', () => {
  beforeEach(() => {
    cy.visit('/index.html')
  })
  it('clicks login button', () => {
    cy.wait(2000)
    cy.get('.modal-footer button[data-auth="login"]').click()
    cy.wait(2000)
    cy.get('#loginEmail')
      .type(Cypress.env('USERNAME'))
      .wait(2000)
      .should('have.value', Cypress.env('USERNAME'))

    cy.get('#loginPassword')
      .type(Cypress.env('PASSWORD'))
      .should('have.value', Cypress.env('PASSWORD'))
    cy.get(`button[type="submit"]`).contains('Login').click()
    cy.wait(2000)
    cy.get('.profile-email').contains(Cypress.env('USERNAME'))
  })
  it('logout', () => {
    cy.wait(2000)
    cy.get('.modal-footer button[data-auth="login"]').click()
    cy.wait(2000)
    cy.get('#loginEmail')
      .type(Cypress.env('USERNAME'))
      .should('have.value', Cypress.env('USERNAME'))
    cy.get('#loginPassword')
      .type(Cypress.env('PASSWORD'))
      .should('have.value', Cypress.env('PASSWORD'))
    cy.get(`button[type="submit"]`).contains('Login').click()
    cy.wait(2000)
    cy.get(`button[data-auth="logout"]`).click()
    cy.wait(2000)
    cy.get('#registerModalLabel')
    cy.timeout(2000).should('be.visible')
  })
})
